//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionListProduction
    {
        public int DistributionListProductionID { get; set; }
        public int DistributionListID { get; set; }
        public int ProductionID { get; set; }
    
        public virtual Production Production { get; set; }
        public virtual DistributionList DistributionList { get; set; }
    }
}
