//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutSystem.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScoutSystemDevEntities : DbContext
    {
        public ScoutSystemDevEntities()
            : base("name=ScoutSystemDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<ScoutDailyReport> ScoutDailyReport { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<DistributionList> DistributionList { get; set; }
        public virtual DbSet<DistributionListCategory> DistributionListCategory { get; set; }
        public virtual DbSet<DistributionListProduction> DistributionListProduction { get; set; }
        public virtual DbSet<ExternalService> ExternalService { get; set; }
        public virtual DbSet<IncidentReport> IncidentReport { get; set; }
        public virtual DbSet<IncidentReportMailingHistory> IncidentReportMailingHistory { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<LocationReport> LocationReport { get; set; }
        public virtual DbSet<LocationReportExternalService> LocationReportExternalService { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
    }
}
