//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationReportExternalService
    {
        public int LocationReportExternalServiceID { get; set; }
        public int LocationReportID { get; set; }
        public int ExternalServiceID { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual ExternalService ExternalService { get; set; }
        public virtual LocationReport LocationReport { get; set; }
    }
}
