//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocationReport()
        {
            this.IncidentReport = new HashSet<IncidentReport>();
            this.LocationReportExternalService = new HashSet<LocationReportExternalService>();
        }
    
        public int LocationReportID { get; set; }
        public int LocationID { get; set; }
        public int ProductionID { get; set; }
        public short UnitID { get; set; }
        public System.TimeSpan SiteStart { get; set; }
        public System.TimeSpan SiteEnd { get; set; }
        public System.TimeSpan ProductionStart { get; set; }
        public System.TimeSpan CateringArrival { get; set; }
        public System.TimeSpan CateringEnd { get; set; }
        public System.TimeSpan PoliceArrival { get; set; }
        public System.TimeSpan PoliceShift { get; set; }
        public System.TimeSpan PoliceEnd { get; set; }
        public System.TimeSpan CleaningCrewArrival { get; set; }
        public System.TimeSpan CleaningCrewEnd { get; set; }
        public System.TimeSpan ProductionLunch { get; set; }
        public System.TimeSpan ProductionLunchEnd { get; set; }
        public System.TimeSpan DinnerBreak { get; set; }
        public System.TimeSpan DinnerBreakEnd { get; set; }
        public System.TimeSpan ProductionEnd { get; set; }
        public System.TimeSpan LastVehicle { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Comments { get; set; }
        public string AspUserID { get; set; }
    
        public virtual Production Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReport> IncidentReport { get; set; }
        public virtual Location Location { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationReportExternalService> LocationReportExternalService { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
