//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoutDailyReport
    {
        public int EntryID { get; set; }
        public string UserID { get; set; }
        public int ProductionID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Task { get; set; }
        public int CarNumber { get; set; }
        public int LocationsVisited { get; set; }
        public int LocationOptions { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsDraft { get; set; }
    
        public virtual Production Production { get; set; }
    }
}
